name: Build and deploy

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'yarn.lock'
      - 'package.json'
      - '**/*.md'
    branches:
      - dev
    tags:
      - '*'

permissions:
  contents: read

jobs:
  nuget:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -  
        name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Create and push NuGet package
        run: |
          dotnet pack -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate